name: Run Newman API Tests

on:
  push:
    branches:
      - main  # Replace with the branch where you want to trigger the tests

jobs:
  newman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the Node.js version you need

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Tests
        run: newman run postman_collection.json


